### ISSUE TITLE
Error after configuring

### ISSUE THREAD

**Issue by jfbethlehem** [mikewoudenberg/homeassistant-loqed#1]
I've been trying to set up the loqed hass loqed component, but it gives an error when using the key and token as given by the app.loqed.com site.

Error:

Logger: homeassistant.config_entries
Source: custom_components/loqed/loqed.py:125 
Integration: Loqed 
First occurred: 09:49:27 (1 occurrences) 
Last logged: 09:49:27

Error setting up entry Loqed bridge for loqed
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/loqed/__init__.py", line 108, in async_setup_entry
    webhook_index = await ensure_webhooks(hass, webhook_id, webhook_client)
  File "/config/custom_components/loqed/__init__.py", line 79, in ensure_webhooks
    webhooks = await webhook_client.get_all_webhooks()
  File "/config/custom_components/loqed/loqed.py", line 125, in get_all_webhooks
    return json.loads(body)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Expected results: anything other than an error.

**Comment by mikewoudenberg** [comment]
This does indeed look like an issue with the keys you provided. 
Have you used the following api key as your "API key of bridge"?
<img width="1392" alt="Screenshot 2022-06-01 at 10 17 43" src="https://user-images.githubusercontent.com/5583336/171359831-b112c77e-6e2a-46e3-96db-b3a8dadba998.png">

BTW this repository is more a personal experiment than a battle ready integration. LOQED is currently working on an official integration which should be launched soon
